version: '3.1'
services:
  mysql:
    image: mysql:5.6
    container_name: creativekits-legacy-mysql
    working_dir: /app
    volumes:
      - ./app:/app
      - ./docker/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=creativekits
      - MYSQL_USER=creativekits
      - MYSQL_PASSWORD=12345678
    ports:
      - '1027:3306'

  nginx:
    image: nginx:alpine
    container_name: creativekits-legacy-webserver
    working_dir: /app
    volumes:
      - ./app:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '1025:80'

  php-fpm:
    build: docker/php-fpm
    container_name: creativekits-legacy-php-fpm
    working_dir: /app
    volumes:
      - ./app:/app
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
